"use client";

import { useMemo, useState } from "react";
import "./mom.css";

type Asset = { symbol: string; name: string; market: string; price: string; change: string; score: number; state: string; tone: "green" | "amber" | "red"; attention: number; sentiment: number; volume: string; narrative: string; signals: { label: string; value: number; color: string }[]; bars: number[] };
const assets: Asset[] = [
  { symbol: "NVDA", name: "NVIDIA Corporation", market: "NASDAQ", price: "$182.41", change: "+4.82%", score: 87, state: "Momentum trade", tone: "amber", attention: 96, sentiment: 88, volume: "3.0×", narrative: "Price broke above its 20-day trend while attention accelerated sharply. Momentum is strong, but social heat is now a risk factor.", signals: [{ label: "Price action", value: 91, color: "#b9ed68" }, { label: "Capital flow", value: 72, color: "#75c9ff" }, { label: "Social sentiment", value: 88, color: "#cf9dff" }, { label: "Attention", value: 96, color: "#ffb86b" }], bars: [48,52,47,59,56,68,71,63,78,73,85,81,91,88,96,92,100,94,98,100] },
  { symbol: "BTC-USD", name: "Bitcoin / US Dollar", market: "CRYPTO", price: "$116,840", change: "+2.14%", score: 74, state: "Attention rising", tone: "green", attention: 82, sentiment: 76, volume: "1.8×", narrative: "Crypto discussion is broadening across retail channels. Price action remains constructive, with moderate crowding risk.", signals: [{ label: "Price action", value: 78, color: "#b9ed68" }, { label: "Capital flow", value: 69, color: "#75c9ff" }, { label: "Social sentiment", value: 76, color: "#cf9dff" }, { label: "Attention", value: 82, color: "#ffb86b" }], bars: [54,49,57,61,58,65,62,69,67,73,71,76,72,78,74,82,79,84,80,86] },
  { symbol: "TSLA", name: "Tesla, Inc.", market: "NASDAQ", price: "$329.18", change: "-1.36%", score: 52, state: "Mixed signals", tone: "red", attention: 89, sentiment: 44, volume: "1.3×", narrative: "Attention remains elevated, but sentiment is diverging from price. The system flags a crowded, two-sided tape.", signals: [{ label: "Price action", value: 46, color: "#b9ed68" }, { label: "Capital flow", value: 51, color: "#75c9ff" }, { label: "Social sentiment", value: 44, color: "#cf9dff" }, { label: "Attention", value: 89, color: "#ffb86b" }], bars: [72,78,75,81,77,70,74,69,63,67,60,64,57,61,55,59,51,55,48,52] },
  { symbol: "AAPL", name: "Apple Inc.", market: "NASDAQ", price: "$218.67", change: "+0.62%", score: 61, state: "Steady trend", tone: "green", attention: 57, sentiment: 64, volume: "0.9×", narrative: "A mature attention profile and steady trend keep Apple in the low-volatility quadrant.", signals: [{ label: "Price action", value: 66, color: "#b9ed68" }, { label: "Capital flow", value: 62, color: "#75c9ff" }, { label: "Social sentiment", value: 64, color: "#cf9dff" }, { label: "Attention", value: 57, color: "#ffb86b" }], bars: [45,47,49,48,52,54,51,55,57,56,59,58,61,60,63,62,64,63,65,66] },
];
const news = [["08:42", "NVIDIA discussion velocity hits 30-day high", "Reddit · r/stocks", "#b9ed68"], ["08:18", "Retail attention broadens beyond mega-cap AI", "MarketPulse RSS", "#75c9ff"], ["07:56", "Tesla sentiment splits as delivery debate returns", "Stocktwits proxy", "#ff8b9e"], ["07:31", "BTC options activity points to event-driven week", "MarketPulse RSS", "#ffb86b"]];
const momThemes = [{ theme: "CPO / 光通信", ticker: "515880", score: 68, buy: 76, sell: 19, signal: "追涨升温", color: "#ffb86b" }, { theme: "半导体 / 存储", ticker: "512480", score: 64, buy: 72, sell: 15, signal: "买入冲动", color: "#b9ed68" }, { theme: "AI 算力", ticker: "159363", score: 58, buy: 61, sell: 22, signal: "讨论扩散", color: "#cf9dff" }, { theme: "黄金", ticker: "518880", score: 43, buy: 18, sell: 57, signal: "恐慌卖出", color: "#75c9ff" }];
const socialHot = [{ rank: "01", symbol: "NVDA", name: "NVIDIA", mentions: "38.4K", growth: "+248%", sentiment: "82% bullish", sources: "Reddit · X · RSS", tone: "positive" }, { rank: "02", symbol: "中际旭创", name: "CPO / 光模块", mentions: "21.7K", growth: "+186%", sentiment: "76% bullish", sources: "雪球 · 股吧", tone: "positive" }, { rank: "03", symbol: "TSLA", name: "Tesla", mentions: "18.2K", growth: "+94%", sentiment: "44% bullish", sources: "X · Reddit", tone: "warning" }, { rank: "04", symbol: "BTC", name: "Bitcoin", mentions: "16.9K", growth: "+71%", sentiment: "68% bullish", sources: "Reddit · RSS", tone: "positive" }];
function scoreClass(tone: Asset["tone"]) { return tone === "green" ? "positive" : tone === "red" ? "negative" : "warning"; }

export default function Home() {
  const [activeSymbol, setActiveSymbol] = useState("NVDA"); const [query, setQuery] = useState(""); const [range, setRange] = useState("24H"); const [saved, setSaved] = useState(false);
  const active = assets.find((asset) => asset.symbol === activeSymbol) ?? assets[0]; const filtered = useMemo(() => assets.filter((asset) => `${asset.symbol} ${asset.name}`.toLowerCase().includes(query.toLowerCase())), [query]);
  return <main className="shell">
    <header className="topbar"><div className="brand"><span className="brand-mark">◒</span><span>MARKET<span className="brand-accent">PULSE</span></span><span className="beta">BETA</span></div><div className="top-status"><span className="live-dot" /> LIVE DEMO <span className="status-divider" /> DATA REFRESHED 2M AGO</div><button className="icon-button" aria-label="Open settings">⋯</button></header>
    <div className="workspace"><aside className="sidebar"><div className="sidebar-heading"><span>WATCHLIST</span><button className="add-button" aria-label="Add asset">＋</button></div><label className="search"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search assets" /></label><div className="list-label">US EQUITIES <span>4</span></div><div className="asset-list">{filtered.map((asset) => <button key={asset.symbol} className={`asset-row ${asset.symbol === active.symbol ? "selected" : ""}`} onClick={() => setActiveSymbol(asset.symbol)}><span className={`asset-pulse ${scoreClass(asset.tone)}`} /><span className="asset-name"><strong>{asset.symbol}</strong><small>{asset.name}</small></span><span className="asset-quote"><strong>{asset.price}</strong><small className={asset.change.startsWith("-") ? "negative" : "positive"}>{asset.change}</small></span></button>)}</div><div className="list-label">MARKET PULSE <span>3</span></div><div className="pulse-list"><div><span className="pulse-icon">⌁</span><span><strong>AI infrastructure</strong><small>Hotspot · 92</small></span><em className="positive">+12</em></div><div><span className="pulse-icon cool">◌</span><span><strong>Crypto majors</strong><small>Building · 74</small></span><em className="positive">+6</em></div><div><span className="pulse-icon hot">△</span><span><strong>EV / mobility</strong><small>Cooling · 48</small></span><em className="negative">−9</em></div></div><div className="sidebar-foot"><span className="mini-avatar">MP</span><span><strong>MarketPulse AI</strong><small>Signal desk</small></span><span className="more">•••</span></div></aside>
      <section className="content"><div className="content-header"><div><div className="eyebrow">ASSET INTELLIGENCE / {active.market}</div><h1>{active.symbol} <span>{active.name}</span></h1><div className="price-line"><strong>{active.price}</strong><span className={active.change.startsWith("-") ? "negative" : "positive"}>{active.change}</span><small>Today · 09:30 ET</small></div></div><div className="header-actions"><button className={`outline-button ${saved ? "saved" : ""}`} onClick={() => setSaved(!saved)}>{saved ? "★ Saved" : "☆ Watch"}</button><button className="outline-button">Share ↗</button></div></div>
        <div className="tabs"><button className="active">Overview</button><button>Signals</button><button>Discussion</button><button>News flow</button><div className="tab-spacer" /><span className="tiny-label">WINDOW</span>{["24H", "7D", "30D"].map((item) => <button key={item} className={`range ${range === item ? "active" : ""}`} onClick={() => setRange(item)}>{item}</button>)}</div>
        <div className="intel-grid"><div className="panel mom-panel"><div className="panel-top"><div><span className="panel-kicker">RETAIL FOMO RADAR / EXPERIMENTAL</span><h2>宝妈指数 <span className="title-note">新手买入与卖出情绪</span></h2></div><span className="demo-badge">DEMO DATA</span></div><div className="mom-intro">不是“宝妈推荐榜”。它观察公开讨论里新手式上车、追涨和恐慌卖出信号。</div><div className="mom-list">{momThemes.map((item) => <div className="mom-row" key={item.theme}><div className="mom-theme"><i style={{ background: item.color }} /><strong>{item.theme}</strong><small>ETF {item.ticker}</small></div><div className="mom-meter"><span>热度</span><div><i style={{ width: `${item.score}%`, background: item.color }} /></div><b>{item.score}</b></div><div className="mom-intent"><span className="positive">买 {item.buy}</span><span className="negative">卖 {item.sell}</span></div><em style={{ color: item.color }}>{item.signal}</em></div>)}</div><div className="mom-foot"><span>样本窗口 · 24H</span><span>来源 · 股吧 / RSS / 社交讨论</span><span className="warning">⚠ 未代表真实持仓</span></div></div><div className="panel social-panel"><div className="panel-top"><div><span className="panel-kicker">SOCIAL PLATFORM HEAT</span><h2>社交平台热议股 <span className="title-note">跨平台讨论加速</span></h2></div><span className="live-label"><i /> LIVE DEMO</span></div><div className="social-head"><span>RANK</span><span>ASSET</span><span>MENTIONS</span><span>24H GROWTH</span><span>SENTIMENT</span></div>{socialHot.map((item) => <div className="social-row" key={item.symbol}><span className="social-rank">{item.rank}</span><div className="social-asset"><strong>{item.symbol}</strong><small>{item.name}</small></div><span className="social-metric">{item.mentions}<small>{item.sources}</small></span><strong className="positive social-growth">{item.growth}</strong><span className={`sentiment ${item.tone}`}>{item.sentiment}</span></div>)}<div className="social-foot">热议 ≠ 推荐 · 每条信号需回溯原文、作者与时间戳</div></div></div>
        <div className="hero-grid"><div className="panel chart-panel"><div className="panel-top"><div><span className="panel-kicker">PRICE ACTION</span><h2>Momentum profile</h2></div><span className="chart-key"><i /> price <i className="violet" /> attention</span></div><div className="chart-wrap"><div className="chart-gridlines"><span /><span /><span /><span /></div><div className="chart-labels"><span>185</span><span>180</span><span>175</span><span>170</span></div><div className="chart-bars">{active.bars.map((height, index) => <span key={`${active.symbol}-${index}`} style={{ height: `${height}%` }} className={index > active.bars.length - 5 ? "hot-bar" : ""} />)}</div><div className="chart-line" /></div><div className="chart-footer"><span><i className="legend-green" /> Trend <strong className="positive">Bullish</strong></span><span><i className="legend-blue" /> Volume <strong>Abnormal</strong></span><span><i className="legend-amber" /> RSI <strong>68.4</strong></span><span>Updated 2m ago</span></div></div><div className="panel score-panel"><div className="panel-top"><div><span className="panel-kicker">SHORT-TERM MARKET SCORE</span><h2>Signal composite</h2></div><span className={`state-badge ${scoreClass(active.tone)}`}>● {active.state}</span></div><div className="score-main"><div className="score-ring" style={{ "--score": `${active.score * 3.6}deg` } as React.CSSProperties}><div><strong>{active.score}</strong><small>/100</small></div></div><p>{active.narrative}</p></div><div className="signal-list">{active.signals.map((signal) => <div className="signal-row" key={signal.label}><span>{signal.label}</span><div className="signal-track"><i style={{ width: `${signal.value}%`, background: signal.color }} /></div><strong>{signal.value}</strong></div>)}</div></div></div>
        <div className="lower-grid"><div className="panel attention-panel"><div className="panel-top"><div><span className="panel-kicker">RETAIL FOMO INDEX</span><h2>Attention is accelerating</h2></div><span className="score-pill">{active.attention} <small>/ 100</small></span></div><div className="attention-body"><div className="attention-gauge"><div className="gauge-fill" style={{ width: `${active.attention}%` }} /><div className="gauge-marker" style={{ left: `${active.attention}%` }} /></div><div className="gauge-scale"><span>ICE COLD</span><span>NORMAL</span><span>HEATING UP</span><span>FOMO ZONE</span></div><div className="attention-stats"><div><span>DISCUSSION GROWTH</span><strong className="positive">+{active.symbol === "NVDA" ? "248" : "106"}%</strong><small>vs. 24h ago</small></div><div><span>SENTIMENT ACCELERATION</span><strong className="positive">+18.6 pts</strong><small>bullish bias</small></div><div><span>VOLUME ANOMALY</span><strong>{active.volume}</strong><small>vs. 20D avg</small></div></div></div></div><div className="panel risk-panel"><div className="panel-top"><div><span className="panel-kicker">RISK RADAR</span><h2>What could change?</h2></div><span className="radar-icon">⌁</span></div><div className="risk-item"><span className="risk-dot high" /><div><strong>Social overheating</strong><small>Retail sentiment is moving faster than price.</small></div><b>HIGH</b></div><div className="risk-item"><span className="risk-dot medium" /><div><strong>Event proximity</strong><small>Macro catalyst window in 3 days.</small></div><b>MED</b></div><div className="risk-item"><span className="risk-dot low" /><div><strong>Trend integrity</strong><small>Price structure remains constructive.</small></div><b>LOW</b></div></div></div>
        <div className="bottom-grid"><div className="panel news-panel"><div className="panel-top"><div><span className="panel-kicker">SIGNAL STREAM</span><h2>Latest market intelligence</h2></div><button className="text-button">View all ↗</button></div>{news.map(([time, title, source, color]) => <div className="news-row" key={title}><time>{time}</time><span className="news-bullet" style={{ background: color }} /><div><strong>{title}</strong><small>{source}</small></div><span className="news-arrow">↗</span></div>)}</div><div className="panel methodology"><span className="panel-kicker">ABOUT THE SCORE</span><h2>Evidence over prediction.</h2><p>MarketPulse combines market structure, attention velocity and crowd sentiment to identify market states—not future prices.</p><div className="method-tags"><span>Transparent</span><span>Timestamped</span><span>Source-aware</span></div><div className="disclaimer">◈ Educational research tool · Not investment advice</div></div></div><footer className="footer"><span>© 2026 MARKETPULSE AI</span><span>DATA SOURCES <b>Market data · RSS · Reddit</b></span><span>BUILD <b>v0.1.0-demo</b></span></footer></section>
    </div>
  </main>;
}
